[package]
name = "voronoi"
version = "0.1.0"
edition = "2024"

[dependencies]
rustacuda = "0.1"
rustacuda_core = "0.1"
rustacuda_derive = "0.1"
image = "0.25"
rand = "0.9"

[build-dependencies]
cc = "1.2"
